version: "3.9"

# commented lines are some things I tried in order to try to resolve the error

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      # mysql:
      #   condition: service_healthy
  mysql:
    image: mysql
    # ports:
    #   - "3306:3306"
    # volumes:
    #   - ./db:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_NAME=url_shortener
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10